esphome:
  name: meshcore-ble-link
  friendly_name: Meshcore ble link

external_components:
  - source:
      type: local
      path: components
    components: [meshcore_ble_bridge]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

esp32_ble:
  io_capability: keyboard_only
  max_connections: 6

logger:
  level: DEBUG
  logs:
    esp32_ble_tracker: DEBUG
    esp32_ble_client: DEBUG
    ble_client: DEBUG
    meshcore_ble_bridge: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Meshcore-Ble-Link"
    password: "xxx"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 2000ms
    window: 1000ms

ble_client:
  - mac_address: AC:A7:04:07:CE:21
    id: meshcore_ble
    auto_connect: true

    on_passkey_request:
      then:
        - logger.log:
            format: "Authenticating MeshCore BLE passkey"
            level: DEBUG
        - ble_client.passkey_reply:
            id: meshcore_ble
            passkey: xxx

meshcore_ble_bridge:
  id: meshcore_bridge
  ble_client_id: meshcore_ble
  port: 5000
  force_encryption: true
  wait_for_auth: true
